package org.example.enums;

public enum TipoMaterial {

    MADEIRA,
    PEDRA,
    METAL,
    RESULTADO_PEDRA_PEDRA,
    RESULTADO_PEDRA_MADEIRA,
    RESULTADO_MADEIRA_MADEIRA,
    RESULTADO_MADEIRA_METAL,
    RESULTADO_PEDRA_METAL,
    RESULTADO_METAL_METAL;

}
